export const DEFAULT_SUBSCRIPTION_CATEGORY = "Subscription";

export const SERVICE_GROUP_OPTIONS = [
  "Video Streaming",
  "Music Streaming",
  "Gaming",
  "AI Tools",
  "Productivity",
  "Developer Tools",
  "Design Tools",
  "Cloud Storage",
  "Security",
  "News and Media",
  "Education",
  "Fitness and Wellness",
  "Banking",
  "Fintech",
  "Mobile Carrier",
  "Internet Provider",
  "Delivery and Retail",
  "Utilities",
  "Other",
];

export const SUBSCRIPTION_NAME_OPTIONS = [
  "Netflix",
  "Spotify",
  "YouTube Premium",
  "Apple Music",
  "Apple TV+",
  "Disney+",
  "Hulu",
  "Max",
  "Prime Video",
  "Paramount+",
  "Peacock",
  "Crunchyroll",
  "Twitch Turbo",
  "SoundCloud Go+",
  "Deezer",
  "Tidal",
  "Audible",
  "Kindle Unlimited",
  "Notion",
  "Slack",
  "Microsoft 365",
  "Google One",
  "Dropbox",
  "iCloud+",
  "Adobe Creative Cloud",
  "Figma",
  "Canva Pro",
  "Grammarly",
  "ChatGPT Plus",
  "GitHub Copilot",
  "JetBrains",
  "Linear",
  "Airtable",
  "Miro",
  "Zapier",
  "Make",
  "1Password",
  "Bitwarden Premium",
  "NordVPN",
  "ExpressVPN",
  "Surfshark",
  "Proton",
  "Proton Drive",
  "Todoist",
  "Trello",
  "Asana",
  "ClickUp",
  "X Premium",
  "LinkedIn Premium",
  "Medium Membership",
  "Substack",
  "The New York Times",
  "The Wall Street Journal",
  "Blinkist",
  "Coursera Plus",
  "Duolingo Super",
  "Babbel",
  "MasterClass",
  "Skillshare",
  "Udemy Personal Plan",
  "Headspace",
  "Calm",
  "Strava",
  "Fitbod",
  "MyFitnessPal Premium",
  "Nike Training Club",
  "Peloton",
  "Xbox Game Pass",
  "PlayStation Plus",
  "Nintendo Switch Online",
  "EA Play",
  "Ubisoft+",
  "GeForce NOW",
  "Amazon Prime",
  "Walmart+",
  "Instacart+",
  "Uber One",
  "DoorDash DashPass",
  "Revolut Premium",
  "Monzo Plus",
  "YNAB",
  "TradingView",
  "Xero",
  "QuickBooks",
  "FreshBooks",
  "Squarespace",
  "Shopify",
  "Webflow",
  "Wix",
  "Heroku",
  "Vercel",
  "Railway",
  "DigitalOcean",
  "Cloudflare Pro",
  "MongoDB Atlas",
  "OpenAI API",
  "ElevenLabs",
  "Perplexity Pro",
  "Claude Pro",
];
